---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang:1.12
  commands:
  - go build -v
  - go test -v -race ./...
  environment:
    # -race requires cgo
    CGO_ENABLED: 1
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org
