---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang:1.12
  commands:
  - go build
  - go test
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
