---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang:1.12
  commands:
  - go test -v -race ./...
  environment:
    # -race requires cgo
    CGO_ENABLED: 1
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: build
  pull: always
  image: golang:1.12
  commands:
  - go build -v
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: tags
  image: golang:1.12
  commands:
  - echo -n "$(git rev-parse --abbrev-ref HEAD | tr / -)-$(date +%Y-%m-%d)-$(git rev-parse --short HEAD),latest" > .tags
  when:
    branch:
    - master
    event:
    - push

- name: docker
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/observatorium/thanos-receive-controller
    password:
      from_secret: quay_password
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-test
  image: plugins/docker
  settings:
    dry_run: true
    repo: quay.io/observatorium/thanos-receive-controller
  when:
    branch:
    event:
    - pull-request
