apiVersion: v1
data:
  hashrings.json: |-
    [
      {
        "hashring": "default",
        "tenants": [

        ]
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/version: master-2019-10-18-d55fee2
  name: thanos-receive-controller-tenants
  namespace: thanos
