apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-tenants
  namespace: default
data:
  config.yaml: |
    - hashring: hashring0
      tenants:
        - foo7
        - bar
    - hashring: hashring1
      tenants:
        - baz
      endpoints: []
