apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-tenants
  namespace: default
data:
  config.yaml: |
    - hashring: hashring0
      tenants:
        - foo
        - bar
    - hashring: hashring1
      tenants:
        - baz
      endpoints: []
---
apiVersion: v1
kind: Service
metadata:
  name: hashring0
  namespace: default
spec:
  clusterIP: None
  selector:
    hashring.thanos.io: hashring0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hashring0
  namespace: default
  labels:
    hashring.thanos.io: hashring0
    controller.receive.thanos.io: thanos-receive-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      hashring.thanos.io: hashring0
  serviceName: hashring0
  template:
    metadata:
      labels:
        hashring.thanos.io: hashring0
    spec:
      containers:
        - args:
            - receive
            - --remote-write.address=0.0.0.0:19291
            - --grpc-address=0.0.0.0:10901
          image: improbable/thanos:v0.5.0
          name: thanos-store
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 19291
              name: remote-write
